namespace: tenant-b

commonLabels:
  geo: uk

resources:
- ../../base/namespace

patches:
- target:
    kind: RoleBinding
    name: tenant-sync
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: ns-reconciler-tenant-b
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-b
    - op: replace
      path: /metadata/annotations/cnrm.cloud.google.com~1project-id
      value: PROJECT-INSERT
- target:
    kind: RepoSync
    name: repo-sync
  patch: |-
    - op: replace
      path: /spec/git/repo
      value: https://github.com/ejmadkins/acm-multi-repo-tenant-b.git